---
#
#   Copyright 2021 binx.io B.V.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# This example cloudbuild shows you how to use the IAP proxy into the
# GKE cluster from cloudbuild.
#
steps:
- id: generate-certificate
  name: ${_SIMPLE_IAP_PROXY}
  args:
    - generate-certificate
    - --key-file
    - server.key
    - --certificate-file
    - server.crt
    - --dns-name
    - simple-iap-proxy

- id: simple-iap-proxy
  name: gcr.io/cloud-builders/docker
  entrypoint: sh
  secretEnv:
    - AUDIENCE
    - TARGET_URL
    - SERVICE_ACCOUNT
  args:
    - -c
    - docker run -d --rm
      -v /workspace:/workspace -w /workspace
      --network cloudbuild --name simple-iap-proxy
      ${_SIMPLE_IAP_PROXY}
      gke-client
      --target-url $$TARGET_URL
      --iap-audience $$AUDIENCE
      --service-account $$SERVICE_ACCOUNT
      --use-default-credentials
      --key-file server.key
      --certificate-file server.crt
      --port 8080

- id: get-credentials
  name: gcr.io/cloud-builders/gcloud
  args:
    - gcloud 
    - container 
    - clusters
    - get-credentials 
    - --internal-ip
    - ${_CLUSTER_NAME}
    - --zone 
    - ${_CLUSTER_ZONE}

- id: setup-k8s
  name: gcr.io/cloud-builders/kubectl
  entrypoint: /bin/sh
  args:
    - -c
    - context_name=$(kubectl config current-context) &&
      kubectl config set clusters.$context_name.certificate-authority-data "$(base64 < server.crt)" &&
      kubectl config set clusters.$context_name.proxy-url https://simple-iap-proxy:8080 &&
      kubectl cluster-info

availableSecrets:
  secretManager:
    - env: AUDIENCE
      versionName: projects/${PROJECT_ID}/secrets/simple-iap-proxy-audience/versions/latest
    - env: SERVICE_ACCOUNT
      versionName: projects/${PROJECT_ID}/secrets/simple-iap-proxy-service-account/versions/latest
    - env: TARGET_URL
      versionName: projects/${PROJECT_ID}/secrets/simple-iap-proxy-target-url/versions/latest

substitutions:
  _SIMPLE_IAP_PROXY: 'gcr.io/binx-io-public/simple-iap-proxy:e8877d6'
  _CLUSTER_NAME: cluster7
  _CLUSTER_ZONE: europe-west4-c
